import fs from 'fs';
import path from 'path';

// --- Utility Functions ---

/**
 * Converts a string from snake_case or camelCase to PascalCase.
 * @param {string} str The input string.
 * @returns {string} The PascalCased string.
 */
const toPascalCase = (str) =>
  str.replace(/(^\w|[-_](\w))/g, (match, p1, p2) => (p2 ? p2.toUpperCase() : p1.toUpperCase()));

/**
 * Naively pluralizes a word.
 * @param {string} str The input string.
 * @returns {string} The pluralized string.
 */
const pluralize = (str) => (str.endsWith('s') ? str : `${str}es`);

/**
 * Naively singularizes a word.
 * @param {string} str The input string.
 * @returns {string} The singularized string.
 */
const singularize = (str) => {
    if (str.endsWith('ies')) return str.slice(0, -3) + 'y';
    if (str.endsWith('s')) return str.slice(0, -1);
    return str;
}

/**
 * Maps a Zod type definition string to a TypeScript type string.
 * @param {string} zodDef The Zod definition string.
 * @returns {string} The corresponding TypeScript type.
 */
const mapZodToTsType = (zodDef) => {
  if (zodDef.startsWith('z.string')) return 'string';
  if (zodDef.startsWith('z.number')) return 'number';
  if (zodDef.startsWith('z.boolean')) return 'boolean';
  if (zodDef.startsWith('z.date')) return 'Date';
  if (zodDef.includes('z.instanceof(Buffer)')) return 'Buffer';
  if (zodDef.startsWith('z.enum')) {
    const matches = zodDef.match(/z\.enum\(\[(.*?)\]\)/);
    if (matches) {
      return matches[1].replace(/,\s*/g, ' | ');
    }
  }
  return 'any';
};

// --- Core Logic ---

/**
 * Analyzes the content of a schema file to extract schema definitions.
 * @param {string} fileContent The content of the schema file.
 * @returns {Array<Object>} An array of analyzed schema objects.
 */
const analyzeSchemas = (fileContent) => {
  const schemaRegex = /export const (\w+?)Schema = z\.object\({([\s\S]+?)}\);/g;
  const schemas = [...fileContent.matchAll(schemaRegex)];
  
  return schemas.map(match => {
    const schemaName = match[1]; // e.g., 'Personality'
    const schemaBody = match[2];
    
    const fieldRegex = /^\s*(\w+):\s*(.*?)(,)?\s*$/gm;
    const fields = [...schemaBody.matchAll(fieldRegex)];
    
    const parsedSchema = {
      name: schemaName,
      augmentedName: `Augmented${schemaName}`,
      dataName: `${schemaName}Data`,
      accessorName: pluralize(schemaName.charAt(0).toLowerCase() + schemaName.slice(1)),
      primitives: [],
      belongsTo: [],
      oneToMany: [],
    };
    
    fields.forEach(fieldMatch => {
      const fieldName = fieldMatch[1];
      const zodDef = fieldMatch[2].trim();
      const isOptional = zodDef.includes('.optional()');

      // One-to-Many relationship: z.lazy(() => z.array(OtherSchema))
      const oneToManyMatch = zodDef.match(/z\.lazy\(\(\) => z\.array\((\w+?)Schema\)\)/);
      if (oneToManyMatch) {
        const relatedSchemaName = oneToManyMatch[1];
        parsedSchema.oneToMany.push({
          fieldName,
          isOptional,
          relatedName: relatedSchemaName,
          singularAccessor: singularize(fieldName),
        });
        return;
      }
      
      // Belongs-To relationship: z.lazy(() => OtherSchema)
      const belongsToMatch = zodDef.match(/z\.lazy\(\(\) => (\w+?)Schema\)/);
      if (belongsToMatch) {
        const relatedSchemaName = belongsToMatch[1];
        parsedSchema.belongsTo.push({
          fieldName,
          isOptional,
          relatedName: relatedSchemaName,
          foreignKey: `${fieldName}Id`,
        });
        return;
      }
      
      // Primitive field
      const hasDefault = zodDef.includes('.default(');
      parsedSchema.primitives.push({
        name: fieldName,
        type: mapZodToTsType(zodDef),
        isOptionalOnCreate: isOptional || hasDefault,
        isOptionalOnEntity: isOptional,
      });
    });
    
    return parsedSchema;
  });
};

/**
 * Generates the TypeScript type definitions as a string.
 * @param {Array<Object>} analyzedSchemas The array of analyzed schema objects.
 * @returns {string} The full content for the types.ts file.
 */
const generateTypeFileContent = (analyzedSchemas) => {
  const preamble = `/**
 * This file is auto-generated by the SatiDB types generator.
 * Do not edit this file manually.
 */\n
import type { Buffer } from 'buffer';
import type { SatiDB as SatiDBClient } from './satidb'; // Adjust this path if needed
\n`;

  const genericTypes = `// --- GENERIC UTILITY TYPES ---\n
// Describes the data needed to create a new instance of an entity.
export type CreateData<T> = Omit<T, 'id' | keyof AugmentedMethods<any> | 'update' | 'delete' | (() => any) | object>;

// Describes the standard methods attached to every SatiDB entity instance.
export type AugmentedMethods<T, D> = {
  update: (data: Partial<D>) => T | null;
  delete: () => void;
};

// Describes the accessor object for a one-to-many relationship (e.g., author.posts).
export type OneToManyAccessor<T, D> = {
  insert: (data: D) => T;
  get: (conditions: string | Partial<T>) => T | null;
  findOne: (conditions: Record<string, any>) => T | null;
  find: (conditions?: Record<string, any>) => T[];
  update: (id: string, data: Partial<D>) => T | null;
  upsert: (conditions?: Partial<T>, data: Partial<D>) => T;
  delete: (id?: string) => void;
  push: (data: D) => T;
};

// Describes a top-level accessor on the DB object (e.g., db.authors).
export type EntityAccessor<T, D> = {
    insert: (data: D) => T;
    get: (conditions: string | Partial<T>) => T | null;
    findOne: (conditions: Record<string, any>) => T | null;
    find: (conditions?: Record<string, any>) => T[];
    update: (id: string, data: Partial<D>) => T | null;
    upsert: (conditions?: Partial<T>, data: Partial<D>) => T;
    delete: (id: string) => void;
    subscribe: (event: 'insert' | 'update' | 'delete', callback: (data: T) => void) => void;
};
\n`;
  
  let dataDefs = `// --- DATA TYPES FOR CREATION ---\n`;
  analyzedSchemas.forEach(schema => {
    dataDefs += `export type ${schema.dataName} = {\n`;
    schema.primitives.forEach(p => {
      dataDefs += `  ${p.name}${p.isOptionalOnCreate ? '?' : ''}: ${p.type};\n`;
    });
    // For creation, you can also specify related entities by their ID
    schema.belongsTo.forEach(r => {
        dataDefs += `  ${r.fieldName}${r.isOptional ? '?' : ''}: { id: string } | string;\n`
    });
    dataDefs += '};\n\n';
  });
  
  let augmentedDefs = `// --- AUGMENTED ENTITY TYPES ---\n`;
  analyzedSchemas.forEach(schema => {
    const relatedDataName = `${schema.name}Data`;
    augmentedDefs += `export type ${schema.augmentedName} = {\n`;
    augmentedDefs += `  id: string;\n`;
    // Primitives
    schema.primitives.forEach(p => {
      augmentedDefs += `  ${p.name}${p.isOptionalOnEntity ? '?' : ''}: ${p.type};\n`;
    });
    // Belongs-To relationships (e.g., authorId and author())
    schema.belongsTo.forEach(r => {
      const relatedSchema = analyzedSchemas.find(s => s.name === r.relatedName);
      augmentedDefs += `  ${r.foreignKey}${r.isOptional ? '?' : ''}: string | null;\n`;
      augmentedDefs += `  ${r.fieldName}: () => ${relatedSchema.augmentedName} | null;\n`;
    });
    // One-to-Many relationships (e.g., posts and post())
    schema.oneToMany.forEach(r => {
      const relatedSchema = analyzedSchemas.find(s => s.name === r.relatedName);
      augmentedDefs += `  ${r.fieldName}${r.isOptional ? '?' : ''}: OneToManyAccessor<${relatedSchema.augmentedName}, ${relatedSchema.dataName}>;\n`;
      augmentedDefs += `  ${r.singularAccessor}: (id: string) => ${relatedSchema.augmentedName} | null;\n`;
    });
    // Standard methods
    augmentedDefs += `} & AugmentedMethods<${schema.augmentedName}, ${relatedDataName}>;\n\n`;
  });
  
  // DB Type Definition
  let dbTypeDef = `// --- DATABASE CLIENT TYPE ---\n\n`;
  dbTypeDef += `export type DB<S> = SatiDBClient<S> & {\n`
  analyzedSchemas.forEach(schema => {
      dbTypeDef += `  ${schema.accessorName}: EntityAccessor<${schema.augmentedName}, ${schema.dataName}>;\n`
  });
  dbTypeDef += `};\n`;

  return preamble + genericTypes + dataDefs + augmentedDefs + dbTypeDef;
};


// --- Main Execution ---

const main = () => {
  const inputFile = process.argv[2];
  const outputFile = process.argv[3];
  
  if (!inputFile || !outputFile) {
    console.error('Usage: bun generate-types.js <path/to/schemas.ts> <path/to/output/types.ts>');
    process.exit(1);
  }
  
  try {
    const schemaFileContent = fs.readFileSync(inputFile, 'utf-8');
    const analyzed = analyzeSchemas(schemaFileContent);
    const typeFileContent = generateTypeFileContent(analyzed);
    fs.writeFileSync(outputFile, typeFileContent);
    
    console.log(`✅ Successfully generated types at ${outputFile}`);
  } catch (error) {
    console.error(`❌ Error generating types: ${error.message}`);
    process.exit(1);
  }
};

main();